#!/usr/bin/env bash
# One-time setup: Configure npm to use GitHub CLI authentication automatically
# After running this, npm will always use your gh token - no manual token management!

set -e

echo "🔧 Setting up automatic GitHub authentication for npm"
echo ""

# Check if gh is installed
if ! command -v gh &> /dev/null; then
  echo "❌ Error: GitHub CLI (gh) is not installed"
  echo "Install it first: brew install gh"
  exit 1
fi

# Check if authenticated
if ! gh auth status &> /dev/null 2>&1; then
  echo "🔐 Not authenticated with GitHub CLI"
  echo "Running: gh auth login"
  gh auth login
fi

# Add package scopes if needed
echo "Checking token scopes..."
SCOPES=$(gh auth status 2>&1 | grep "Token scopes" | head -1 || echo "")
if [[ ! "$SCOPES" =~ "write:packages" ]]; then
  echo "Adding package scopes to your gh token..."
  gh auth refresh -h github.com -s read:packages,write:packages
else
  echo "✓ Token already has package scopes"
fi

# Detect shell
SHELL_RC=""
if [ -n "$ZSH_VERSION" ]; then
  SHELL_RC="$HOME/.zshrc"
elif [ -n "$BASH_VERSION" ]; then
  SHELL_RC="$HOME/.bashrc"
else
  echo "⚠️  Could not detect shell. Please manually add to your shell config:"
  echo ""
  echo "    export NODE_AUTH_TOKEN=\$(gh auth token)"
  echo ""
  exit 1
fi

# Check if already configured
if grep -q "NODE_AUTH_TOKEN.*gh auth token" "$SHELL_RC" 2>/dev/null; then
  echo "✓ Shell already configured"
else
  echo ""
  echo "Adding NODE_AUTH_TOKEN to $SHELL_RC"
  echo ""
  echo "# GitHub npm authentication (auto-generated by mcp-server-kit setup)" >> "$SHELL_RC"
  echo 'export NODE_AUTH_TOKEN=$(gh auth token)' >> "$SHELL_RC"
  echo ""
  echo "✓ Added to $SHELL_RC"
fi

# Create/update ~/.npmrc
echo ""
echo "Configuring ~/.npmrc..."
mkdir -p "$HOME"

NPMRC="$HOME/.npmrc"
if [ ! -f "$NPMRC" ]; then
  touch "$NPMRC"
fi

# Add registry config if not present
if ! grep -q "@MikeC-A6:registry" "$NPMRC" 2>/dev/null; then
  echo "//npm.pkg.github.com/:_authToken=\${NODE_AUTH_TOKEN}" >> "$NPMRC"
  echo "@MikeC-A6:registry=https://npm.pkg.github.com/" >> "$NPMRC"
  echo "always-auth=true" >> "$NPMRC"
  echo "✓ Configured ~/.npmrc"
else
  echo "✓ ~/.npmrc already configured"
fi

# Apply to current session
export NODE_AUTH_TOKEN=$(gh auth token)

echo ""
echo "✅ Setup complete!"
echo ""
echo "To use immediately in this terminal, run:"
echo "  source $SHELL_RC"
echo ""
echo "Or just open a new terminal - it will work automatically."
echo ""
echo "Test it:"
echo "  npm install @MikeC-A6/mcp-server-kit"
echo ""
